### ISSUE TITLE
PyOpenGL and Android

### ISSUE THREAD

**Issue by mak8kammerer** [mcfletch/pyopengl#103]
Hi there!
Is it possible to run PyOpenGL on Android OS? Are there any examples?

**Comment by mcfletch** [comment]
I haven't touched Android development in years. My strong suspicion is that anyone looking at Python + GLES on Android is likely choosing Kivy rather than raw Python + PyOpenGL. See e.g. https://kivy.org/doc/stable/examples/gen__3Drendering__main__py.html
HTH.

**Comment by cmbruns** [comment]
Now that python 3.13 and 3.14 have official android support it might be time to reopen this.

I am the developer of pyopenxr, and I am actively trying to support android; especially the Meta Quest 3 VR headset.
I built cpython 3.14 for android, and installed numpy and PyOpenGL. Many things are working well. 
On my journey toward creating a meaningful example, my latest road block is within PyOpenGL.
I suspect we only need a little more platform detection nuance to go forward.

On the Quest 3 HMD, with Python 3.14:

  `sys.platform == "android"`
  `os.name == "posix"`
  `platform.system() == "Android"`
```
  >>> os.environ
environ({'PATH': '/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ANDROID_ART_ROOT': '/apex/com.android.art', 'ANDROID_I18N_ROOT': '/apex/com.android.i18n', 'ANDROID_TZDATA_ROOT': '/apex/com.android.tzdata', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'DOWNLOAD_CACHE': '/data/cache', 'BOOTCLASSPATH': '/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/framework-graphics.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system_ext/framework/com.oculus.os.platform.jar:/system_ext/framework/hzos-framework.jar:/system_ext/framework/ocui.jar:/apex/com.android.i18n/javalib/core-icu4j.jar:/apex/com.android.adservices/javalib/framework-adservices.jar:/apex/com.android.adservices/javalib/framework-sdksandbox.jar:/apex/com.android.appsearch/javalib/framework-appsearch.jar:/apex/com.android.btservices/javalib/framework-bluetooth.jar:/apex/com.android.configinfrastructure/javalib/framework-configinfrastructure.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.devicelock/javalib/framework-devicelock.jar:/apex/com.android.healthfitness/javalib/framework-healthfitness.jar:/apex/com.android.ipsec/javalib/android.net.ipsec.ike.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.ondevicepersonalization/javalib/framework-ondevicepersonalization.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.permission/javalib/framework-permission-s.jar:/apex/com.android.scheduling/javalib/framework-scheduling.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.tethering/javalib/framework-connectivity.jar:/apex/com.android.tethering/javalib/framework-connectivity-t.jar:/apex/com.android.tethering/javalib/framework-tethering.jar:/apex/com.android.uwb/javalib/framework-uwb.jar:/apex/com.android.virt/javalib/framework-virtualization.jar:/apex/com.android.wifi/javalib/framework-wifi.jar', 'DEX2OATBOOTCLASSPATH': '/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/framework-graphics.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system_ext/framework/com.oculus.os.platform.jar:/system_ext/framework/hzos-framework.jar:/system_ext/framework/ocui.jar:/apex/com.android.i18n/javalib/core-icu4j.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/com.android.location.provider.jar:/system/framework/services.jar:/system_ext/framework/horizonos-services.jar:/system_ext/framework/oculus-system-services.jar:/apex/com.android.adservices/javalib/service-adservices.jar:/apex/com.android.adservices/javalib/service-sdksandbox.jar:/apex/com.android.appsearch/javalib/service-appsearch.jar:/apex/com.android.art/javalib/service-art.jar:/apex/com.android.configinfrastructure/javalib/service-configinfrastructure.jar:/apex/com.android.healthfitness/javalib/service-healthfitness.jar:/apex/com.android.media/javalib/service-media-s.jar:/apex/com.android.ondevicepersonalization/javalib/service-ondevicepersonalization.jar:/apex/com.android.permission/javalib/service-permission.jar:/apex/com.android.rkpd/java
```

The minimal synopsis I am trying to support at the moment is below. It runs correctly on Linux, but it fails on Android.

```python
# EGL use synopsis. This works on Linux. Desire is to have it work on Android too.

from OpenGL import EGL

# 1. Get EGL display
display = EGL.eglGetDisplay(EGL.EGL_DEFAULT_DISPLAY)
assert display != EGL.EGL_NO_DISPLAY

# 2. Initialize EGL
major, minor = EGL.EGLint(), EGL.EGLint()
assert EGL.eglInitialize(display, major, minor)

# 3. Choose config
config_attributes = [
    EGL.EGL_RENDERABLE_TYPE, EGL.EGL_OPENGL_ES3_BIT,
    EGL.EGL_SURFACE_TYPE, EGL.EGL_PBUFFER_BIT,
    EGL.EGL_RED_SIZE, 8, EGL.EGL_GREEN_SIZE, 8, EGL.EGL_BLUE_SIZE, 8,
    EGL.EGL_ALPHA_SIZE, 8, EGL.EGL_DEPTH_SIZE, 24,
    EGL.EGL_NONE]
num_configs = EGL.EGLint()
configs = (EGL.EGLConfig * 1)()
assert EGL.eglChooseConfig(display, config_attributes, configs, 1, num_configs)
assert num_configs.value > 0
config = configs[0]

# 4. Create 1×1 pixel PBuffer surface
pbuffer_attributes = [
    EGL.EGL_WIDTH, 1,
    EGL.EGL_HEIGHT, 1,
    EGL.EGL_NONE]
surface = EGL.eglCreatePbufferSurface(display, config, pbuffer_attributes)
assert surface != EGL.EGL_NO_SURFACE

# 5. Create GLES3 context
context_attributes = [
    EGL.EGL_CONTEXT_CLIENT_VERSION, 3,
    EGL.EGL_NONE
]
context = EGL.eglCreateContext(display, config, EGL.EGL_NO_CONTEXT, context_attributes)
assert context != EGL.EGL_NO_CONTEXT

# 6. Make context current
assert EGL.eglMakeCurrent(display, surface, surface, context)

# 7. Make context not current
assert EGL.eglMakeCurrent(display, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
```

When run on the Quest 3:
```
Traceback (most recent call last):
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/glx.py", line 46, in GLX
    lib = ctypesloader.loadLibrary(
        ctypes.cdll, name, mode=ctypes.RTLD_GLOBAL
    )
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/data/data/org.bruns.hellopython/files/python314.zip/ctypes/__init__.py", line 462, in __init__
    self._handle = _dlopen(self._name, mode)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
OSError: ('dlopen failed: library "GLX" not found', 'GLX', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/EGL/__init__.py", line 2, in <module>
    from OpenGL.raw.EGL._types import *
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/raw/EGL/_types.py", line 4, in <module>
    from OpenGL import platform as _p
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/__init__.py", line 59, in <module>
    _load()
    ~~~~~^^
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/__init__.py", line 55, in _load
    plugin.install(globals())
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/baseplatform.py", line 108, in install
    namespace[name] = getattr(self, name, None)
                      ~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/baseplatform.py", line 19, in __get__
    value = self.fget(obj)
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/glx.py", line 104, in GetCurrentContext
    glXGetCurrentContext = self.GLX.glXGetCurrentContext
                           ^^^^^^^^
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/baseplatform.py", line 19, in __get__
    value = self.fget(obj)
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/glx.py", line 52, in GLX
    return self.GL
           ^^^^^^^
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/baseplatform.py", line 19, in __get__
    value = self.fget(obj)
  File "/data/data/org.bruns.hellopython/files/site-packages/OpenGL/platform/glx.py", line 24, in GL
    raise ImportError("Unable to load OpenGL or GL library")
ImportError: Unable to load OpenGL or GL library
<...finished running script egl_synopsis.py !>
```

There is no GLX on android. So at the very least we probably want to skip the GLX stuff on this platform.
