### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'maxint' when importing OpenGL.Tk in python 3.7

### ISSUE THREAD

**Issue by alandmoore** [mcfletch/pyopengl#16]
Using Python 3.7 on Arch Linux, installed PyOpenGL-3.1.0 from pypi.

When importing OpenGL.Tk, I get the following:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alanm/.local/lib/python3.7/site-packages/OpenGL/Tk/__init__.py", line 102, in <module>
    if sys.maxint > 2**32:
AttributeError: module 'sys' has no attribute 'maxint'
```

**Comment by mcfletch** [comment]
Updated to use `sys.maxsize`

**Comment by mcfletch** [comment]
Should be fixed in 3.1.3b2

**Comment by alandmoore** [comment]
This particular bug is fixed now, yes.

**Comment by arnualien** [comment]
Thanks (sys.maxsize) works
